### ISSUE TITLE
Keep going and Try again buttons not working in Safari on iOS 16

### ISSUE THREAD

**Issue by kuglee** [stepheneb/elm-2048#12]
Thanks for the game! It's pretty great, but unfortunately the Keep going and Try again buttons are not working in Safari on iOS 16.

**Comment by stepheneb** [comment]
I've noticed this also on my iPhone in Safari. Not present in Chrome 107 on my macOS. Will test on desktop Safari before investigating further.

**Comment by stepheneb** [comment]
Not a problem on Safari running on the desktop ...
